
services:
  web_server:
    image: nginx:alpine
    volumes:
      - ${SITE_PATH}:/var/www/app
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - '80:80'
      - '443:443'
    networks:
      - laravel
    environment:
      TZ: Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  php:
    build: ./php/${PHP_VERSION}
    volumes:
      - ${SITE_PATH}:/var/www/app
    environment:
      TZ: Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - laravel
    restart: unless-stopped
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    networks:
      - laravel
  redis:
    image: redis:latest
    networks:
      - laravel
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - laravel
  adminer:
      image: dockette/adminer:full
      ports:
        - '${INTERFACE}:8080:80'
      environment:
        UPLOAD: 1024M # upload_max_filesize, post_max_size
      networks:
        - laravel
volumes:
  postgres-data:

networks:
  laravel:
